version: "3.1"

services:
  spk_mst:
    image: mkenjis/ubpyspk1_img
    environment:
      - SPARK_HOST_SLAVES=spk_wkr1,spk_wkr2,spk_wkr3
    ports:
      - 8082:8082
    networks:
      - mynet
    depends_on:
      - spk_wkr1,spk_wkr2,spk_wkr3
  spk_wkr1:
    image: mkenjis/ubpyspk1_img
    networks:
      - mynet
  spk_wkr2:
    image: mkenjis/ubpyspk1_img
    networks:
      - mynet
  spk_wkr3:
    image: mkenjis/ubpyspk1_img
    networks:
      - mynet

networks:
  mynet:
    external:
       name: mynet